### ISSUE TITLE
DomainUnderTest check is not strict enough

### ISSUE THREAD

**Issue by DaveAurionix** [purplebricks/Pat.Subscriber#23]
### Problem
When service tests run for a particular domain, they can trigger errors in child domains.  For example a service test using a DomainUnderTest of `GP.Finance.Pledges.MilestoneBased` will publish events that are correctly picked up by a component named `GP.Finance.Pledges.MilestoneBased.Subscriber` but are also (undesirably) picked up by a component named `GP.Finance.Pledges.MilestoneBased.Conversion.Subscriber` (the .Conversion part of the namespace is different).

### Desired behaviour
Instead, we need to allow service tests to be written that target components in the `GP.Finance.Pledges.MilestoneBased` domain and a separate set of tests written that target components in the `GP.Finance.Pledges.MilestoneBased.Conversion` domain. The two sets of service tests do not cause side-effects in each other's domains.

### Cause
When Pat Subscribers receive an event, they examine the DomainUnderTest header (if any) and check that their Subscriber name begins with that value.  This does not prevent components in subdomains from picking up messages meant only for parent domains.  This was a deliberate design choice that was originally made to allow wider system integration tests between all components in a given domain.  Unfortunately I now think that the more common use case is for targeted service tests.  Wider system-integration tests in a microservice world are more likely to be far fewer in number, probably UI-driven and using "real" data not stubbed behaviour - e.g. known test users, known test addresses, etc.

### Proposed solution
We stop supporting (for now) wider integration tests (I'm not aware that PB have any of these?).  When Pat builds the DomainUnderTest filter, we add a clause that limits the messages allowed through to just those where the subscriber's name is exactly one level deeper than the DomainUnderTest (as well as starting with the DomainUnderTest), in other words, for a DomainUnderTest of `A.B.C`, the following would apply:

Subscriber | Match (proposed behaviour) | Match (current behaviour)
--- | --- | ---
A.B.C.Subscriber | Yes | Yes
A.B.C.ServiceTests | Yes | Yes
A.B.C.D.Subscriber | No | Yes
A.B.C.D.ServiceTest | No | Yes
A.B.Subscriber | No | No

There is a more complex solution possible if we need to retain the ability to perform wider integration tests … but I don't like complexity unless essential!

@srpeirce @ilivewithian @AndyRB can you see any problems or would it be OK for me to put a PR together?

**Comment by ilivewithian** [comment]
The change you're proposing doesn't clash with any of our current use-cases, so on that level ✔️ 

I understand why you want the change, but isn't that going to add confusion into the way the filters work? The simple `.StartsWith` rule is very simple to understand and work with. My concern might be resolvable with decent documentation.

I did wonder if the issue your raise points to a smell around the way you've modeled the domain/subdomains. Clearly I don't know your domain and the example posted seem legit. Would modelling your domain be a better fix, or is it really something Pat needs to solve?

**Comment by AndyRB** [comment]
@DaveAurionix you define GP.Finance.Pledges.MilestoneBased.Conversion not as a sub-domain of GP.Finance.Pledges.MilestoneBased, but just as a separate domain entirely?
I think a lot comes down to the scope of the tests, which for us were by design meant to cover the wider service boundary (the domain) including all collaborating micro-services (AC's) within that boundary.
If we going to change this design decision then I think I'd need to understand that what we have is fundamentally not the right approach. Perhaps be worth understanding your domain more to help understand which  is the better approach, I can certainly see arguments for either approach.

**Comment by DaveAurionix** [comment]
@ilivewithian @AndyRB Yep, thank you.

I think we've got badly named services as a result of iterative delivery without looking far enough ahead.

Easier example (apologies for the context switch):

# What we did

Sprint 1, we develop and release:
`GP.Fundraisers.Challenges` - a microservice, _we thought_ (with tests)
`GP.Fundraisers.Challenges.WebApi` - a component, _we thought_
At that point in time everything looked simple and we thought was correct.

Sprint 2, we identify, develop and release:
`GP.Fundraisers.Challenges.ActivityRecords` - a microservice (with tests)
`GP.Fundraisers.Challenges.ActivityRecords.Subscriber` - a component
`GP.Fundraisers.Challenges.ActivityRecords.WebApi` - a component
At this point in time, any messages published during service tests around work in sprint 1 get picked up by Pat in sprint 2's microservices and (undesirably) handled as real messages not synthetic (due to the domain check).  What went wrong is that `GP.Fundraisers.Challenges` just became a domain in sprint 2, not a micro-service, but we never noticed (or rather: never thought about the immediate impact on previously written services).

# What we should have done

Sprint 1:
`GP.Fundraisers.Challenges` - domain
`GP.Fundraisers.Challenges.Details` - a microservice (with tests)
`GP.Fundraisers.Challenges.Details.WebApi` - a component within the microservice

Sprint 2 (same as before):
`GP.Fundraisers.Challenges.ActivityRecords` - a microservice (with tests)
`GP.Fundraisers.Challenges.ActivityRecords.Subscriber` - a component
`GP.Fundraisers.Challenges.ActivityRecords.WebApi` - a component

I'll run this past others here at GivePenny, I'll re-open the issue if we're not in agreement.  We've got a lot of horrible renaming to do but that'll teach us to get it right next time...
